# Generated by Django 5.0 on 2025-02-05 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination", "0004_alter_examination_totdate"),
        ("letter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="letter",
            name="examination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="letters",
                to="examination.examination",
            ),
        ),
    ]
