# Generated by Django 5.0 on 2025-02-09 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "letter",
            "0003_letter_cc_letter_created_at_letter_hotel_letter_meal_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="letter",
            old_name="memebershipOrFellowship",
            new_name="membershipOrFellowship",
        ),
    ]
