# Generated by Django 5.0 on 2025-02-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letter", "0004_rename_memebershiporfellowship_letter_membershiporfellowship"),
    ]

    operations = [
        migrations.AddField(
            model_name="letter",
            name="countryOfTheExamination",
            field=models.CharField(default="Nigeria", max_length=200),
        ),
        migrations.AddField(
            model_name="letter",
            name="faculty",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="letter",
            name="holdAt",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="letter",
            name="onOrBefore",
            field=models.CharField(default="tomorrow", max_length=200),
        ),
    ]
