# Generated by Django 5.0 on 2025-02-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letter", "0005_letter_countryoftheexamination_letter_faculty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="letter",
            name="countryOfTheExamination",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="letter",
            name="onOrBefore",
            field=models.CharField(default="", max_length=200),
        ),
    ]
