# Generated by Django 5.0 on 2025-02-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letter", "0006_alter_letter_countryoftheexamination_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="letter",
            name="InstitutionAddressCountry",
            field=models.CharField(default="", max_length=300),
        ),
    ]
