# Generated by Django 5.0 on 2025-02-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letter", "0007_letter_institutionaddresscountry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="letter",
            name="cc",
            field=models.CharField(default="", max_length=400),
        ),
        migrations.AlterField(
            model_name="letter",
            name="hotel",
            field=models.CharField(default="", max_length=400),
        ),
        migrations.AlterField(
            model_name="letter",
            name="meal",
            field=models.CharField(default="", max_length=400),
        ),
    ]
