# Generated by Django 5.0 on 2025-02-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letter", "0008_alter_letter_cc_alter_letter_hotel_alter_letter_meal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="letter",
            name="arrivalDate",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="letter",
            name="depatureDate",
            field=models.CharField(max_length=200),
        ),
    ]
