# Generated by Django 5.0 on 2025-03-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letter", "0009_alter_letter_arrivaldate_alter_letter_depaturedate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="letter",
            name="arrivalDate",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="letter",
            name="depatureDate",
            field=models.CharField(default="", max_length=20),
        ),
    ]
