# Generated by Django 5.0 on 2025-03-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letter", "0010_alter_letter_arrivaldate_alter_letter_depaturedate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="letter", name="email", field=models.CharField(max_length=200),
        ),
    ]
