# Generated by Django 5.0 on 2025-03-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letter", "0011_alter_letter_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="letter",
            name="userType",
            field=models.CharField(default="", max_length=200),
        ),
    ]
