# Generated by Django 5.0 on 2025-05-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0012_letter_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='status',
            field=models.CharField(default='Letter not sent', max_length=200),
        ),
    ]
