# Generated by Django 5.0 on 2025-05-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0013_letter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='status',
            field=models.CharField(default='Not Sent', max_length=200),
        ),
    ]
