# Generated by Django 5.0 on 2025-02-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Examination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("examName", models.CharField(max_length=200)),
                ("totTopic", models.CharField(max_length=200)),
                ("totFlyers", models.ImageField(upload_to="")),
                ("totDate", models.DateField(auto_now_add=True)),
                ("totDetails", models.TextField()),
                ("timetableIbadan", models.FileField(upload_to="")),
                ("timetableAccra", models.FileField(upload_to="")),
                ("timetableAbuja", models.FileField(upload_to="")),
                ("travelProtocol", models.FileField(upload_to="")),
            ],
        ),
    ]
