# Generated by Django 5.0 on 2025-02-02 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Letter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surname", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("institutionAddress", models.CharField(max_length=300)),
                ("centerOfTheExamination", models.CharField(max_length=200)),
                ("arrivalDate", models.DateField()),
                ("depatureDate", models.DateField()),
                ("email", models.CharField(max_length=60)),
                (
                    "examination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="examination.examination",
                    ),
                ),
            ],
        ),
    ]
