# Generated by Django 5.0 on 2025-02-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination", "0003_delete_letter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examination", name="totDate", field=models.DateField(),
        ),
    ]
