# Generated by Django 5.0 on 2025-02-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination", "0004_alter_examination_totdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examination",
            name="timetableIbadan",
            field=models.FileField(upload_to="uploads/"),
        ),
    ]
