# Generated by Django 5.0 on 2025-02-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination", "0005_alter_examination_timetableibadan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examination",
            name="timetableAbuja",
            field=models.FileField(upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="examination",
            name="timetableAccra",
            field=models.FileField(upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="examination",
            name="totFlyers",
            field=models.ImageField(upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="examination",
            name="travelProtocol",
            field=models.FileField(upload_to="uploads/"),
        ),
    ]
