# Generated by Django 5.0 on 2025-03-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination", "0006_alter_examination_timetableabuja_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examination",
            name="totDate",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="examination",
            name="totFlyers",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
