# Generated by Django 5.0 on 2025-03-07 08:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("examination", "0007_alter_examination_totdate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examination",
            name="totDetails",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
