# Generated by Django 5.0 on 2025-03-07 09:39

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("examination", "0008_alter_examination_totdetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examination",
            name="totDetails",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="TOT Details"),
        ),
    ]
