# Generated by Django 5.0 on 2025-05-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0009_alter_examination_totdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='arrivalinfo',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
